// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
    numberOfOrders:          number;
    paidOrders:              number;
    noPaidOrders:            number;
    numberOfClientes:        number;
    numberOfProducts:        number;
    productsWithNoInventory: number;
    lowInventory:            number;
}
